name: Schedule Probe

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduler test
        run: |
          echo "GitHub Scheduler OK"
          echo "UTC time:"
          date -u
